#
name: Deploy to web server

on:
  workflow_dispatch:
  push:
    branches: [actions-debug]

jobs:
  deploy:
    environment: staging
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Show current directory
        run: ls -laR

      - name: SSH to server
        env:
          SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
          REMOTE_USER: ${{ secrets.REMOTE_USER }}
          REMOTE_HOST: ${{ secrets.REMOTE_HOST }}
          REMOTE_PATH: ${{ vars.REMOTE_PATH }}
        run: |
          echo "$SSH_PRIVATE_KEY" > private_key && chmod 600 private_key
          rsync -avz --delete \
            -e "ssh -i private_key -o StrictHostKeyChecking=no" \
            _site $REMOTE_USER@$REMOTE_HOST:$REMOTE_PATH/
          rm -f private_key
